all:
	./manage.py makemigrations
	./manage.py migrate
	./manage.py runserver 0.0.0.0:8000

run:
	./manage.py runserver 0.0.0.0:8000

init:
	workon my_django_environment
	./manage.py runserver 0.0.0.0:8000

